import { test, expect } from '@playwright/test'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

/**
 * End-to-end encode flow using --stub-llm (no Ollama required).
 *
 * Proves the full chain: React Library page, REST /api/library,
 * Encoder page, REST /api/encoder/start, WebSocket /ws/encoder/{id},
 * real ffmpeg frame + spectrogram extraction, stub classifier,
 * bundle writing, completion event.
 *
 * The synthetic test video is generated by global-setup.ts at the
 * start of the Playwright run and placed under
 * REELDESC_E2E_CONFIG_DIR/media/test.mp4.
 */

const E2E_DIR =
  process.env.REELDESC_E2E_CONFIG_DIR ?? join(tmpdir(), 'reeldesc-e2e')
const MEDIA_DIR = join(E2E_DIR, 'media')

test.describe('Encode flow (stub_llm)', () => {
  test.beforeEach(async ({ request }) => {
    // Seed settings: point Library at the tmpdir media dir, enable
    // stub LLM so no Ollama is needed, faster fps so the run
    // finishes quickly.
    await request.put('/api/settings', {
      data: {
        media_roots: [MEDIA_DIR],
        ollama_instances: [],  // empty — stub_llm means no workers needed
        ha: {
          base_url: 'http://homeassistant.local:8123',
          token: '',
          media_player_entity: 'media_player.living_room',
        },
        encoding_defaults: {
          fps: 0.5,
          confidence_threshold: 0.7,
          two_pass: false,
          stub_llm: true,
        },
        ui: { theme: 'dark', notify_on_complete: false },
      },
    })
  })

  test('Library → Encoder → Start → Done → Open in Editor', async ({ page }) => {
    // Library shows test.mp4
    await page.goto('/')
    await expect(page.getByText('test.mp4')).toBeVisible()

    // Click Encode on the unencoded file
    await page.getByRole('button', { name: /Encode/ }).click()

    // Encoder page loads with the filename
    await expect(page).toHaveURL(/\/encoder\?video=/)
    await expect(page.getByRole('heading', { name: 'test.mp4' })).toBeVisible()

    // Click Start Encode
    await page.getByRole('button', { name: /Start Encode/ }).click()

    // Wait for completion — the "Open in Editor" button appears when done.
    // Generous timeout: extraction + stub classify + compress on a 10s
    // video is fast but not instant.
    const openInEditor = page.getByRole('button', { name: 'Open in Editor' })
    await expect(openInEditor).toBeVisible({ timeout: 90_000 })

    // Clicking navigates to the Editor with the bundle path
    await openInEditor.click()
    await expect(page).toHaveURL(/\/editor\?path=/)
  })
})
